[tool.poetry]
name = "eda_analysis"
version = "0.1.0"
description = "Conduct inital EDA analysis for exploring data in a dataframe."
authors = ["sweber15 <sarah.weber@live.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
